From: Andrey Somov <py4fun@gmail.com>
To: yaml-core@lists.sourceforge.net
Subject: [ANN] SnakeYAML-1.0rc1: construct type safe collections

=============================
 Announcing SnakeYAML-1.0rc1
=============================

A new release of SnakeYAML is now available:

    http://trac-hg.assembla.com/snakeyaml/

This release implements type safe List and Map as a property of a custom Java class as well as some minor improvements.
All the features for 1.0 are implemented. If no problems are reported 1.0 will be released soon.

Changes
=======

 * Implement type safe List and Map as a property of a custom Java class
 * remove Java 6 dependencies

Resources
=========

SnakeYAML homepage: http://trac-hg.assembla.com/snakeyaml/
SnakeYAML documentation: http://trac-hg.assembla.com/snakeyaml/wiki/Documentation

JAR package: http://www.assembla.com/spaces/snakeyaml/documents/dUI1Qg4-er3zVvab7jnrAJ/download?filename=SnakeYAML-1.0rc1.jar
ZIP archive: http://www.assembla.com/spaces/snakeyaml/documents/cRXSwE4-mr3AJiab7jnrAJ/download?filename=SnakeYAML-all-1.0rc1.zip
Changes: http://snakeyaml.narod.ru/releases/v1.0rc1/site/changes-report.html
SnakeYAML Mercurial repository: http://hg.assembla.com/snakeyaml
Submit a bug report: http://trac-hg.assembla.com/snakeyaml/newticket

YAML homepage: http://yaml.org/
YAML-core mailing list: http://lists.sourceforge.net/lists/listinfo/yaml-core


About SnakeYAML
============

YAML is a data serialization format designed for human readability and
interaction with scripting languages.  SnakeYAML is a YAML parser and
emitter for Java.

SnakeYAML features a complete YAML 1.1 parser.
SnakeYAML is applicable for a broad range of tasks from complex
configuration files to object serialization and persistence.


Copyright
=========

SnakeYAML is developed by Andrey Somov <py4fun@gmail.com>.

SnakeYAML is released under the MIT license.
