From: Andrey Somov <py4fun@gmail.com>
To: yaml-core@lists.sourceforge.net
Subject: [ANN] SnakeYAML-1.0.1: implement Enum support

=============================
 Announcing SnakeYAML-1.0.1
=============================

A new release of SnakeYAML is now available:

    http://trac-hg.assembla.com/snakeyaml/

This release delivers the proper Enum support as well as minor bug fixes.

Changes
=======

 * implement Enum support
 * minor performance improvement
 * fix minor issues in DumperOptions 

Resources
=========

SnakeYAML homepage: http://trac-hg.assembla.com/snakeyaml/
SnakeYAML documentation: http://trac-hg.assembla.com/snakeyaml/wiki/Documentation

JAR package: http://snakeyamlrepo.appspot.com/repository/SnakeYAML/SnakeYAML/1.0.1/SnakeYAML-1.0.1.jar
Reports: http://snakeyamlrepo.appspot.com/

SnakeYAML Mercurial repository: http://hg.assembla.com/snakeyaml
Submit a bug report: http://trac-hg.assembla.com/snakeyaml/newticket

YAML homepage: http://yaml.org/
YAML-core mailing list: http://lists.sourceforge.net/lists/listinfo/yaml-core


About SnakeYAML
============

YAML is a data serialization format designed for human readability and
interaction with scripting languages.  SnakeYAML is a YAML parser and
emitter for Java.

SnakeYAML features a complete YAML 1.1 parser.
SnakeYAML is applicable for a broad range of tasks from complex
configuration files to object serialization and persistence.


Copyright
=========

SnakeYAML is developed by Andrey Somov <py4fun@gmail.com>.

SnakeYAML is released under the MIT license.
